# Generated by Django 4.2.5 on 2023-12-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usosrodales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_usos_rodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariostypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariostypes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervencionestypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencionestypes_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
