# Generated by Django 4.2.5 on 2024-01-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usosrodales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_usos_rodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_categorias', to='configuration.categoriascapas'),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_servicio_ide', to='configuration.serviciosideconfig'),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tilelayer_wms_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviciosideconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_ide_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapconfiggis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_config_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariostypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariostypes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervencionestypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencionestypes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriascapas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoriascapas_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capasbasesdefault',
            name='capabase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capasbase_default_cb', to='configuration.capasbases'),
        ),
        migrations.AddField(
            model_name='capasbasesdefault',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabasedefault_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capasbases',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabase_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
