# Generated by Django 4.2.5 on 2023-12-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usosrodales',
            old_name='nombre',
            new_name='name',
        ),
    ]
