# Generated by Django 4.2.5 on 2024-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriascapas',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Categoria'),
        ),
    ]
