# Generated by Django 4.2.5 on 2023-12-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencionestypes',
            name='color',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Color'),
        ),
    ]
