# Generated by Django 4.2.5 on 2024-01-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_intervencionestypes_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasCapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MapConfigGis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs', models.CharField(blank=True, max_length=45, null=True, verbose_name='CRS')),
                ('center_x', models.FloatField()),
                ('center_y', models.FloatField()),
                ('zoom', models.IntegerField()),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('renderer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tipo de Renderizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosIDEConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL del Servicio')),
            ],
        ),
    ]
