# Generated by Django 4.2.5 on 2024-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_categoriascapas_mapconfiggis_serviciosideconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapconfiggis',
            name='crs',
            field=models.CharField(blank=True, default='L.CRS.EPSG3857', max_length=45, null=True, verbose_name='CRS'),
        ),
    ]
