# Generated by Django 4.2.5 on 2024-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_tilelayerwms_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilelayerwms',
            name='max_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='max_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='min_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tilelayerwms',
            name='min_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
