# Generated by Django 4.2.5 on 2024-01-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_mapconfiggis_crs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapconfiggis',
            name='zoom',
            field=models.FloatField(),
        ),
    ]
