# Generated by Django 4.2.5 on 2024-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_tilelayerwms_max_x_tilelayerwms_max_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilelayerwms',
            name='max_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='max_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='min_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='min_y',
            field=models.FloatField(default=0),
        ),
    ]
