# Generated by Django 4.2.5 on 2024-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_mapconfiggis_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapasBases',
            fields=[
                ('idcapasbase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('urlservice', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL del Servicio')),
                ('attribution', models.CharField(blank=True, max_length=500, null=True, verbose_name='Atribuciones')),
                ('subdomain', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subdominio')),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time')),
                ('tilematrixset', models.CharField(blank=True, max_length=100, null=True, verbose_name='tilematrixset')),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
    ]
