# Generated by Django 4.2.5 on 2024-01-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_capasbases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capasbases',
            old_name='nombre',
            new_name='name',
        ),
    ]
