# Generated by Django 4.2.5 on 2024-01-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_capasbasesdefault_capabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasbasesdefault',
            name='capabase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capasbasedefaultcb', to='configuration.capasbases'),
        ),
    ]
