# Generated by Django 4.2.5 on 2024-04-19 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0010_alter_capasbases_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMateriales',
            fields=[
                ('idcategoriamateriales', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoriasmat_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriasMateriales',
            fields=[
                ('idsubcategoriamateriales', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categorias_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_mat_sub_cat', to='configuration.categoriasmateriales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategoriasmat_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesSAP',
            fields=[
                ('idmaterialessap', models.AutoField(primary_key=True, serialize=False)),
                ('matnr', models.CharField(max_length=200, unique=True, verbose_name='matnr')),
                ('maktx', models.CharField(max_length=200, unique=True, verbose_name='maktx')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categorias_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_matsap', to='configuration.categoriasmateriales')),
                ('subcategorias_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_mat_sap', to='configuration.categoriasmateriales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matsap_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
