# Generated by Django 4.2.5 on 2024-04-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_categoriasmateriales_subcategoriasmateriales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialessap',
            name='categorias_materiales',
        ),
    ]
