# Generated by Django 4.2.5 on 2024-04-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_remove_materialessap_categorias_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialessap',
            name='subcategorias_materiales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_mat_sap', to='configuration.subcategoriasmateriales'),
        ),
    ]
