# Generated by Django 4.2.5 on 2024-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_alter_materialessap_subcategorias_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialessap',
            name='maktx',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='maktx'),
        ),
        migrations.AlterField(
            model_name='materialessap',
            name='matnr',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='matnr'),
        ),
    ]
