# Generated by Django 4.2.5 on 2024-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_alter_materialessap_maktx_alter_materialessap_matnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialessap',
            name='maktx',
            field=models.CharField(blank=True, max_length=200, verbose_name='maktx'),
        ),
    ]
