# Generated by Django 4.2.5 on 2024-04-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodales_gis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodalesgis',
            old_name='area',
            new_name='superficie',
        ),
    ]
