# Generated by Django 4.2.5 on 2023-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales_gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodalesgis',
            name='chacra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chacra'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='manzana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzana'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='parcela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='partida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='seccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='subparcela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subparcela'),
        ),
    ]
