# Generated by Django 4.2.5 on 2024-04-05 04:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0003_remove_rodales_objnr_rodales_sap_id'),
        ('rodales_gis', '0003_remove_rodalesgis_chacra_remove_rodalesgis_manzana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodalesstate',
            name='chacra',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='manzana',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='rodalesstate',
            name='subparcela',
        ),
        migrations.CreateModel(
            name='RodalesParcelas',
            fields=[
                ('rodales_parcelas_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('seccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sección')),
                ('chacra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chacra')),
                ('manzana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzana')),
                ('parcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parcela')),
                ('subparcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subparcela')),
                ('partida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('rodales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodales_rodalesparcelas_gis', to='rodales.rodales')),
            ],
        ),
    ]
