# Generated by Django 4.2.5 on 2023-12-11 17:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodales_gis', '0003_alter_rodalesgis_area_alter_rodalesgis_perimetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodalesgis',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
