# Generated by Django 4.2.5 on 2023-12-11 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodales_gis', '0004_alter_rodalesgis_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodalesgis',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='rodalesgis',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5349),
        ),
    ]
