# Generated by Django 4.2.5 on 2024-08-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_alter_empresas_sap_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo/Empresa')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie de Lote')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('parcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parcela')),
                ('partida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matricula')),
                ('seccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seccion')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('certificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificado')),
                ('superficie_gis', models.FloatField(blank=True, null=True, verbose_name='Superficie GIS')),
                ('superficie_empresa', models.FloatField(blank=True, null=True, verbose_name='Superficie Empresa')),
                ('trat_especial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tratamiento especial')),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catastro_empresas', to='empresas.empresas')),
            ],
        ),
    ]
