# Generated by Django 4.2.5 on 2024-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_catastrogis_delete_catastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastrogis',
            name='certificado',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Certificado'),
        ),
    ]
