# Generated by Django 4.2.5 on 2024-09-21 00:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodales', '0006_rodales_is_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventariosCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarioscat_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventariosRelevamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('type', models.CharField(choices=[('Manual', 'Manual'), ('Dispositivo', 'Dispositivo'), ('Preexistente', 'Preexistente')], max_length=20, verbose_name='Tipo de Relevamiento')),
                ('h_deseada', models.FloatField(blank=True, null=True)),
                ('h_last_poda', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_finish', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('categorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_category', to='inventario.inventarioscategories')),
                ('rodales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_rodales', to='rodales.rodales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosrel_users', to=settings.AUTH_USER_MODEL)),
                ('user_relevador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosrel_users_relevador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenRelevamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arb_ha', models.IntegerField(blank=True, null=True)),
                ('arb_podados', models.IntegerField(blank=True, null=True)),
                ('arb_h_deseada', models.IntegerField(blank=True, null=True)),
                ('arb_no_podados', models.IntegerField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('h_total', models.FloatField(blank=True, null=True)),
                ('h_poda', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('area_basal', models.FloatField(blank=True, null=True)),
                ('copa_rem', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('relevamientos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_resumen', to='inventario.inventariosrelevamientos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosrelres_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventariosParcelasgis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_parcela', models.FloatField(blank=True)),
                ('number_parcela', models.IntegerField(blank=True)),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de Parcela')),
                ('number_trees', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('relevamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parc_invrel', to='inventario.inventariosrelevamientos')),
                ('rodales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parc_rodales', to='rodales.rodales')),
            ],
        ),
        migrations.CreateModel(
            name='InventariosObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosobs_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventariosDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosdam_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArbolesRelevamientoPoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_tree', models.IntegerField(blank=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('h_poda', models.FloatField(blank=True, null=True)),
                ('h_total', models.FloatField(blank=True, null=True)),
                ('is_poda', models.BooleanField(default=False, verbose_name='Podado?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('damages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_arb_poda', to='inventario.inventariosdamages')),
                ('observaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obser_arb_poda', to='inventario.inventariosobservaciones')),
                ('parcela', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invrel_parc_arb', to='inventario.inventariosparcelasgis')),
                ('relevamientos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_arb_poda', to='inventario.inventariosrelevamientos')),
            ],
        ),
        migrations.CreateModel(
            name='ArbolesRelevamientoOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_tree', models.IntegerField(blank=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('h_poda', models.FloatField(blank=True, null=True)),
                ('h_total', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('damages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_arb_others', to='inventario.inventariosdamages')),
                ('observaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_arb_poda', to='inventario.inventariosobservaciones')),
                ('parcela', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invrel_parc_arb_others', to='inventario.inventariosparcelasgis')),
                ('relevamientos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_arb_others', to='inventario.inventariosrelevamientos')),
            ],
        ),
    ]
