# Generated by Django 4.2.5 on 2024-09-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosrelevamientos',
            name='is_finish',
            field=models.BooleanField(default=True, verbose_name='Finalizado'),
        ),
    ]
