# Generated by Django 4.2.5 on 2024-08-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbolesrelevamientopoda',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='inventarioscategories',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventariosdamages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventariosobservaciones',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventariosparcelasgis',
            name='inventarios',
        ),
        migrations.RemoveField(
            model_name='inventariosparcelasgis',
            name='rodales',
        ),
        migrations.RemoveField(
            model_name='inventariosrelevamientos',
            name='rodales',
        ),
        migrations.RemoveField(
            model_name='inventariosrelevamientos',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArbolesRelevamientoOthers',
        ),
        migrations.DeleteModel(
            name='ArbolesRelevamientoPoda',
        ),
        migrations.DeleteModel(
            name='InventariosCategories',
        ),
        migrations.DeleteModel(
            name='InventariosDamages',
        ),
        migrations.DeleteModel(
            name='InventariosObservaciones',
        ),
        migrations.DeleteModel(
            name='InventariosParcelasgis',
        ),
        migrations.DeleteModel(
            name='InventariosRelevamientos',
        ),
    ]
