# Generated by Django 4.2.5 on 2024-09-22 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsefor', '0006_alter_emseformaquinas_cantidad'),
        ('inventario', '0002_alter_inventariosrelevamientos_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosrelevamientos',
            name='emsefor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_emsefor', to='emsefor.emsefor'),
        ),
    ]
