# Generated by Django 4.2.5 on 2024-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsefor', '0006_alter_emseformaquinas_cantidad'),
        ('intervenciones', '0004_alter_intervenciones_type'),
        ('inventario', '0002_inventariosrelevamientos_emsefor_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='resumenrelevamientos',
            name='intervenciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_interv', to='intervenciones.intervenciones'),
        ),
        migrations.AddField(
            model_name='resumenrelevamientos',
            name='is_load_to_intervencion',
            field=models.BooleanField(default=False, verbose_name='Load to Intervenciones?'),
        ),
    ]
