# Generated by Django 4.2.5 on 2024-10-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsefor', '0006_alter_emseformaquinas_cantidad'),
        ('inventario', '0003_inventariosrelevamientos_emsefor_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='resumenrelevamientos',
            name='tam_parcela',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
