# Generated by Django 4.2.5 on 2024-09-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosrelevamientos',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_category', to='inventario.inventarioscategories'),
        ),
    ]
