# Generated by Django 4.2.5 on 2024-09-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_inventariosrelevamientos_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbolesrelevamientoothers',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='arbolesrelevamientoothers',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='arbolesrelevamientopoda',
            name='damages',
        ),
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='damages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_arb_other', to='inventario.inventariosdamages'),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='observaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_arb_poda', to='inventario.inventariosobservaciones'),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientopoda',
            name='damages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_arb_poda', to='inventario.inventariosdamages'),
        ),
    ]
