# Generated by Django 4.2.5 on 2024-10-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsefor', '0006_alter_emseformaquinas_cantidad'),
        ('inventario', '0005_inventariosrelevamientos_emsefor_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='resumenrelevamientos',
            name='relevamientos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_resumen', to='inventario.inventariosrelevamientos'),
        ),
    ]
