# Generated by Django 4.2.5 on 2024-09-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_arbolesrelevamientopoda_relevamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbolesrelevamientopoda',
            old_name='relevamentos',
            new_name='relevamientos',
        ),
    ]
