# Generated by Django 4.2.5 on 2024-09-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_relevamentos_arbolesrelevamientopoda_relevamientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariosparcelasgis',
            old_name='inventarios',
            new_name='relevamiento',
        ),
    ]
