# Generated by Django 4.2.5 on 2024-09-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_inventarios_inventariosparcelasgis_relevamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbolesrelevamientopoda',
            name='parcela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invrel_parc_arb', to='inventario.inventariosparcelasgis'),
        ),
    ]
