# Generated by Django 4.2.5 on 2024-09-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0006_rodales_is_sap'),
        ('inventario', '0009_arbolesrelevamientopoda_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosrelevamientos',
            name='rodales',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_rodales', to='rodales.rodales'),
        ),
    ]
