# Generated by Django 4.2.5 on 2024-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventariosrelevamientos_rodales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosparcelasgis',
            name='number_trees',
            field=models.IntegerField(default=0),
        ),
    ]
