# Generated by Django 4.2.5 on 2024-09-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0006_rodales_is_sap'),
        ('inventario', '0011_inventariosparcelasgis_number_trees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosrelevamientos',
            name='rodales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_rodales', to='rodales.rodales'),
        ),
    ]
