# Generated by Django 4.2.5 on 2024-09-10 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0012_alter_inventariosrelevamientos_rodales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosrelevamientos',
            name='user_relevador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventariosrel_users_relevador', to=settings.AUTH_USER_MODEL),
        ),
    ]
