# Generated by Django 4.2.5 on 2024-09-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_arbolesrelevamientopoda_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='parcela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invrel_parc_arb_others', to='inventario.inventariosparcelasgis'),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='relevamientos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invrel_arb_others', to='inventario.inventariosrelevamientos'),
        ),
        migrations.AlterField(
            model_name='arbolesrelevamientoothers',
            name='damages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_arb_others', to='inventario.inventariosdamages'),
        ),
    ]
