# Generated by Django 4.2.5 on 2024-09-19 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_arbolesrelevamientoothers_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5349),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientoothers',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientopoda',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5349),
        ),
        migrations.AddField(
            model_name='arbolesrelevamientopoda',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
