# Generated by Django 4.2.5 on 2024-09-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_arbolesrelevamientoothers_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosrelevamientos',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Dispositivo', 'Dispositivo'), ('Preexistente', 'Preexistente')], max_length=20, verbose_name='Tipo de Relevamiento'),
        ),
    ]
