# Generated by Django 4.2.5 on 2023-12-26 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionIntervenciones',
            fields=[
                ('planificacionintervencion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('date_start', models.DateField(verbose_name='Fecha de Inicio')),
                ('date_end', models.DateField(verbose_name='Fecha de Finalización')),
                ('status', models.BooleanField(default=False, verbose_name='Realizado?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rodales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodales_planificacion_inter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_planificacion_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
