# Generated by Django 4.2.5 on 2023-12-26 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionintervenciones',
            name='intervenciones_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_types_planificacion_inter', to=settings.AUTH_USER_MODEL),
        ),
    ]
