# Generated by Django 4.2.5 on 2023-12-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_intervencionestypes_color'),
        ('planificacion', '0002_planificacionintervenciones_intervenciones_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionintervenciones',
            name='intervenciones_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_types_planificacion_inter', to='configuration.intervencionestypes'),
        ),
    ]
