# Generated by Django 4.2.5 on 2023-12-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0001_initial'),
        ('planificacion', '0003_alter_planificacionintervenciones_intervenciones_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionintervenciones',
            name='rodales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodales_planificacion_inter', to='rodales.rodales'),
        ),
    ]
