# Generated by Django 4.2.5 on 2023-12-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0005_delete_marker'),
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaciones',
            name='rodales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantaciones_rodales', to='rodales.rodales'),
        ),
    ]
