# Generated by Django 4.2.5 on 2023-12-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0001_initial'),
        ('plantaciones', '0003_alter_plantaciones_rodales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaciones',
            name='plantaciones_gis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantacion_plantaciones_gis', to='gis_pindo.plantacionesgis'),
        ),
    ]
