# Generated by Django 4.2.5 on 2023-12-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0004_alter_plantaciones_plantaciones_gis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantaciones',
            name='plantaciones_gis',
        ),
    ]
