# Generated by Django 4.2.5 on 2023-12-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0006_remove_plantaciones_sobrevivencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaciones',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
