# Generated by Django 4.2.5 on 2024-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedencias',
            fields=[
                ('procedencias_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('mejora', models.CharField(max_length=100, verbose_name='Mejora')),
                ('vivero', models.CharField(max_length=100, verbose_name='Vivero')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.TextField()),
            ],
        ),
    ]
