# Generated by Django 4.2.5 on 2024-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedencias',
            name='material',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Material'),
        ),
    ]
