# Generated by Django 4.2.5 on 2023-12-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervenciones', '0001_initial'),
        ('gis_pindo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaintervenciongis',
            name='intervencion_gis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion_gis', to='intervenciones.intervenciones'),
        ),
    ]
