# Generated by Django 4.2.5 on 2023-12-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0005_remove_plantaciones_plantaciones_gis'),
        ('gis_pindo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacionesgis',
            name='plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantacion_plantaciones_gis', to='plantaciones.plantaciones'),
        ),
    ]
