# Generated by Django 4.2.5 on 2023-12-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalarazaIntervenciongis',
        ),
    ]
