# Generated by Django 4.2.5 on 2024-01-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_pindo', '0002_initial'),
        ('intervenciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talarazaintervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_talaraza_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sobrevivenciaintervenciongis',
            name='intervencion_gis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivencia_intervencion_gis', to='intervenciones.intervenciones'),
        ),
        migrations.AddField(
            model_name='sobrevivenciaintervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_sobrevivencia_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raleointervenciongis',
            name='intervencion_gis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raleo_intervencion_gis', to='intervenciones.intervenciones'),
        ),
        migrations.AddField(
            model_name='raleointervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_raleo_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podaintervenciongis',
            name='intervencion_gis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion_gis', to='intervenciones.intervenciones'),
        ),
        migrations.AddField(
            model_name='podaintervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_poda_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantacionesgis',
            name='plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantacion_plantaciongis', to='plantaciones.plantaciones'),
        ),
        migrations.AddField(
            model_name='plantacionesgis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_plantaciones_gis', to=settings.AUTH_USER_MODEL),
        ),
    ]
