# Generated by Django 4.2.5 on 2023-12-17 05:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0002_plantacionesgis_plantacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacionesgis',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5349),
        ),
        migrations.AddField(
            model_name='plantacionesgis',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
