# Generated by Django 4.2.5 on 2023-12-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis_pindo', '0002_initial'),
        ('plantaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podaintervenciongis',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_poda_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantacionesgis',
            name='plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantacion_plantaciongis', to='plantaciones.plantaciones'),
        ),
        migrations.AddField(
            model_name='plantacionesgis',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_plantaciones_gis', to=settings.AUTH_USER_MODEL),
        ),
    ]
