# Generated by Django 4.2.5 on 2024-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaintervenciongis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='raleointervenciongis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='talarazaintervenciongis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sobrevivenciaintervenciongis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
