# Generated by Django 4.2.5 on 2023-12-19 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_pindo', '0004_alter_plantacionesgis_plantacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacionesgis',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_plantaciones_gis', to=settings.AUTH_USER_MODEL),
        ),
    ]
