# Generated by Django 4.2.5 on 2023-12-19 06:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0007_alter_plantaciones_fecha'),
        ('gis_pindo', '0005_alter_plantacionesgis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodaIntervenciongis',
            fields=[
                ('podaintervenciongis_id', models.AutoField(primary_key=True, serialize=False)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='plantacionesgis',
            name='plantacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantaciones.plantaciones'),
        ),
    ]
