# Generated by Django 4.2.5 on 2023-12-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0006_sobrevivenciaintervenciongis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SobrevivenciaIntervenciongis',
        ),
    ]
