# Generated by Django 4.2.5 on 2023-12-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0008_sobrevivenciaintervenciongis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivenciaintervenciongis',
            name='sibrevivenciaintervenciongis_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
