# Generated by Django 4.2.5 on 2023-12-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0007_alter_plantaciones_fecha'),
        ('intervenciones', '0004_alter_podaintervencion_intervenciones_and_more'),
        ('gis_pindo', '0008_alter_plantacionesgis_plantacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacionesgis',
            name='plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantacion_plantaciongis', to='plantaciones.plantaciones'),
        ),
        migrations.AlterField(
            model_name='podaintervenciongis',
            name='poda_intervencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intervenciones.podaintervencion'),
        ),
    ]
