# Generated by Django 4.2.5 on 2023-12-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0005_remove_podaintervencion_fecha_and_more'),
        ('gis_pindo', '0009_alter_plantacionesgis_plantacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaintervenciongis',
            name='poda_intervencion',
        ),
        migrations.AddField(
            model_name='podaintervenciongis',
            name='intervencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intervenciones.intervenciones'),
        ),
    ]
