# Generated by Django 4.2.5 on 2023-12-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0009_alter_sobrevivenciaintervenciongis_sibrevivenciaintervenciongis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivenciaintervenciongis',
            name='sibrevivenciaintervenciongis_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
