# Generated by Django 4.2.5 on 2023-12-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0005_remove_podaintervencion_fecha_and_more'),
        ('gis_pindo', '0010_remove_podaintervenciongis_poda_intervencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaintervenciongis',
            name='intervencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion_gis', to='intervenciones.intervenciones'),
        ),
    ]
