# Generated by Django 4.2.5 on 2023-12-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0010_alter_sobrevivenciaintervenciongis_sibrevivenciaintervenciongis_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SobrevivenciaIntervenciongis',
        ),
    ]
