# Generated by Django 4.2.5 on 2023-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0011_alter_podaintervenciongis_intervencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podaintervenciongis',
            old_name='intervencion',
            new_name='intervencion_gis',
        ),
    ]
