# Generated by Django 4.2.5 on 2023-12-22 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_pindo', '0012_sobrevivenciaintervenciongis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacionesgis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_plantaciones_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podaintervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_poda_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sobrevivenciaintervenciongis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_sobrevivencia_intervencion_gis', to=settings.AUTH_USER_MODEL),
        ),
    ]
