# Generated by Django 4.2.5 on 2023-12-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_pindo', '0013_alter_plantacionesgis_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivenciaintervenciongis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de Parcela'),
        ),
    ]
