# Generated by Django 4.2.5 on 2023-10-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sagpyas',
            fields=[
                ('sagpyas_id', models.AutoField(primary_key=True, serialize=False)),
                ('operaciones', models.CharField(blank=True, max_length=50, verbose_name='Operaciones')),
                ('fecha', models.DateTimeField(blank=True)),
                ('sup_aprobada', models.FloatField(blank=True)),
                ('expediente', models.CharField(blank=True, max_length=50, verbose_name='Expediente')),
                ('turno_minimo', models.CharField(blank=True, max_length=50, verbose_name='Turno Mínimo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifies', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SagpyasFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to='sagpyas_files/', verbose_name='Files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sagpyas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagpyas_files', to='sagpyas.sagpyas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sagpyas_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
