# Generated by Django 4.2.5 on 2024-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0003_remove_rodales_objnr_rodales_sap_id'),
        ('sagpyas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyas',
            name='rodales',
            field=models.ManyToManyField(related_name='sagpyas_rodales', to='rodales.rodales'),
        ),
    ]
