# Generated by Django 4.2.5 on 2024-07-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagpyasExpedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sagpyas',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='sagpyas',
            name='rodales',
        ),
        migrations.RemoveField(
            model_name='sagpyas',
            name='turno_minimo',
        ),
        migrations.AddField(
            model_name='sagpyas',
            name='expedientes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_sagpya', to='sagpyas.sagpyasexpedientes'),
        ),
    ]
