# Generated by Django 4.2.5 on 2023-10-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sagpyas',
            old_name='modifies',
            new_name='modified',
        ),
    ]
