# Generated by Django 4.2.5 on 2024-07-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0006_rodales_is_sap'),
        ('sagpyas', '0002_sagpyasexpedientes_remove_sagpyas_expediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagpyasRodales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(blank=True, null=True, verbose_name='Turno')),
                ('superficie_aprobada', models.FloatField(blank=True, null=True, verbose_name='Superficie Aprobada')),
                ('rodales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodales_sag', to='rodales.rodales')),
                ('sagpyas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagpyas_rod', to='sagpyas.sagpyas')),
            ],
        ),
    ]
