# Generated by Django 4.2.5 on 2023-10-28 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sagpyas', '0002_rename_modifies_sagpyas_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasfiles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_sagpyas_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
