# Generated by Django 4.2.5 on 2024-07-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sagpyas', '0004_sagpyasexpedientesfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagpyasExpedientesMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_sagpyas_exp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
