# Generated by Django 4.2.5 on 2024-07-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0005_sagpyasexpedientesmovimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasexpedientesmovimientos',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sagpyas_exp_mov', to='sagpyas.sagpyasexpedientes'),
        ),
    ]
