# Generated by Django 4.2.5 on 2024-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0006_sagpyasexpedientesmovimientos_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasexpedientesmovimientos',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
    ]
