# Generated by Django 4.2.5 on 2023-10-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sagpyas', '0007_alter_sagpyasfiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasfiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sagpyas_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
