# Generated by Django 4.2.5 on 2024-07-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0007_sagpyasexpedientesmovimientos_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SagpyasExpedientesFiles',
        ),
    ]
