# Generated by Django 4.2.5 on 2024-07-26 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sagpyas', '0009_sagpyasexpedientesfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasexpedientesmovimientos',
            name='expediente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sagpyas_exp_mov', to='sagpyas.sagpyasexpedientes'),
        ),
        migrations.AlterField(
            model_name='sagpyasexpedientesmovimientos',
            name='user_created',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_sagpyas_exp', to=settings.AUTH_USER_MODEL),
        ),
    ]
