# Generated by Django 4.2.5 on 2024-07-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0010_alter_sagpyasexpedientesmovimientos_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasexpedientesfiles',
            name='sagpyaexp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagpyasexpmov_files', to='sagpyas.sagpyasexpedientesmovimientos'),
        ),
    ]
