# Generated by Django 4.2.5 on 2024-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0011_alter_sagpyasexpedientesfiles_sagpyaexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyas',
            name='expediente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Expediente'),
        ),
    ]
