# Generated by Django 4.2.5 on 2024-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0006_rodales_is_sap'),
        ('sagpyas', '0012_sagpyas_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyas',
            name='rodales',
            field=models.ManyToManyField(through='sagpyas.SagpyasRodales', to='rodales.rodales'),
        ),
    ]
