# Generated by Django 4.2.5 on 2023-10-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0012_alter_sagpyasfiles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagpyasfiles',
            name='user',
        ),
    ]
