# Generated by Django 4.2.5 on 2024-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0013_sagpyas_rodales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasrodales',
            name='tarea',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tarea'),
        ),
    ]
