# Generated by Django 4.2.5 on 2023-10-28 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sagpyas', '0013_remove_sagpyasfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasfiles',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sagpyas_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
