# Generated by Django 4.2.5 on 2023-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0015_alter_sagpyasfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasfiles',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
    ]
