# Generated by Django 4.2.5 on 2023-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0016_sagpyasfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasfiles',
            name='url',
            field=models.CharField(default=None, max_length=250, verbose_name='URL'),
        ),
    ]
