# Generated by Django 4.2.5 on 2024-08-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0016_sagpyasmovimientosfiles_sagpyasmovimientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SagpyasMovimientosFiles',
        ),
    ]
