# Generated by Django 4.2.5 on 2023-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0018_alter_sagpyasfiles_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasfiles',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='URL'),
        ),
    ]
