# Generated by Django 4.2.5 on 2023-11-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0019_alter_sagpyasfiles_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasfiles',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sagpyasfiles',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
