# Generated by Django 4.2.5 on 2023-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0020_sagpyasfiles_description_alter_sagpyasfiles_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagpyasfiles',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
