# Generated by Django 4.2.5 on 2023-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagpyas', '0021_alter_sagpyasfiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagpyasfiles',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='sagpyasfiles',
            name='type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo'),
        ),
    ]
