# Generated by Django 4.2.5 on 2023-12-19 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emsefor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodales', '0005_delete_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('intervenciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('type', models.EmailField(choices=[('Sobrevivencia', 'Sobrevivencia'), ('Poda', 'Poda'), ('Raleo', 'Raleo'), ('Tala Rasa', 'Tala Rasa')], max_length=15, verbose_name='Tipo de Intervencion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('emsefors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencion_emsefor', to='emsefor.emsefor')),
                ('rodales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodales_intervenciones', to='rodales.rodales')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_intervencion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodaIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('arb_podados', models.IntegerField(blank=True, null=True)),
                ('arb_no_podados', models.IntegerField(blank=True, null=True)),
                ('alt_deseada', models.FloatField(blank=True, null=True)),
                ('alt_poda', models.FloatField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('porc_removido', models.FloatField(blank=True, null=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion', to='intervenciones.intervenciones')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_poda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
