# Generated by Django 4.2.5 on 2024-01-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('emsefor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('intervenciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('type', models.EmailField(choices=[('Sobrevivencia', 'Sobrevivencia'), ('Poda', 'Poda'), ('Raleo', 'Raleo'), ('Talaraza', 'Talaraza')], max_length=15, verbose_name='Tipo de Intervencion')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de Intervencion')),
                ('emsefors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencion_emsefor', to='emsefor.emsefor')),
                ('intervenciones_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_type_intervencion', to='configuration.intervencionestypes')),
            ],
        ),
        migrations.CreateModel(
            name='TalarazaIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('criterio', models.CharField(max_length=100, null=True, verbose_name='Criterio')),
                ('arboles_extraidos', models.IntegerField(blank=True, null=True)),
                ('arboles_podados', models.IntegerField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('porc_removido', models.FloatField(blank=True, null=True)),
                ('intensidad', models.FloatField(blank=True, null=True)),
                ('levante', models.FloatField(blank=True, null=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talaraza_intervencion', to='intervenciones.intervenciones')),
            ],
        ),
        migrations.CreateModel(
            name='SobrevivenciaIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parcela_size', models.FloatField(blank=True, null=True)),
                ('parcela_relevadas', models.IntegerField(blank=True, null=True)),
                ('plantas_vivas', models.IntegerField(blank=True, null=True)),
                ('plantas_muertas', models.IntegerField(blank=True, null=True)),
                ('damage_herbicida', models.IntegerField(blank=True, null=True)),
                ('damage_mecanico', models.IntegerField(blank=True, null=True)),
                ('sobrevivencia', models.FloatField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=100, null=True, verbose_name='Responsable')),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivencia_intervencion', to='intervenciones.intervenciones')),
            ],
        ),
        migrations.CreateModel(
            name='RaleoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('criterio', models.CharField(max_length=100, null=True, verbose_name='Criterio')),
                ('arboles_extraidos', models.IntegerField(blank=True, null=True)),
                ('arboles_podados', models.IntegerField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('porc_removido', models.FloatField(blank=True, null=True)),
                ('intensidad', models.FloatField(blank=True, null=True)),
                ('levante', models.FloatField(blank=True, null=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raleo_intervencion', to='intervenciones.intervenciones')),
            ],
        ),
        migrations.CreateModel(
            name='PodaIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('arb_podados', models.IntegerField(blank=True, null=True)),
                ('arb_no_podados', models.IntegerField(blank=True, null=True)),
                ('alt_deseada', models.FloatField(blank=True, null=True)),
                ('alt_poda', models.FloatField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('dmsm', models.FloatField(blank=True, null=True)),
                ('area_basal', models.FloatField(blank=True, null=True)),
                ('porc_removido', models.FloatField(blank=True, null=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion', to='intervenciones.intervenciones')),
            ],
        ),
    ]
