# Generated by Django 4.2.5 on 2023-12-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobrevivenciaIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobrevivencia', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sobreviviencia_intervencion', to='intervenciones.intervenciones')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_sobrevivencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
