# Generated by Django 4.2.5 on 2023-12-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervenciones', '0001_initial'),
        ('rodales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenciones',
            name='rodales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodales_intervenciones', to='rodales.rodales'),
        ),
        migrations.AddField(
            model_name='intervenciones',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_intervencion', to=settings.AUTH_USER_MODEL),
        ),
    ]
