# Generated by Django 4.2.5 on 2023-12-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivenciaintervencion',
            name='responsable',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
    ]
