# Generated by Django 4.2.5 on 2023-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0003_sobrevivenciaintervencion_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaintervencion',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de Intervencion'),
        ),
        migrations.AddField(
            model_name='sobrevivenciaintervencion',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de Intervencion'),
        ),
    ]
