# Generated by Django 4.2.5 on 2024-04-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0003_intervenciones_planificacion_inter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenciones',
            name='type',
            field=models.CharField(choices=[('Sobrevivencia', 'Sobrevivencia'), ('Poda', 'Poda'), ('Raleo', 'Raleo'), ('Talaraza', 'Talaraza')], max_length=15, verbose_name='Tipo de Intervencion'),
        ),
    ]
