# Generated by Django 4.2.5 on 2023-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0004_podaintervencion_name_sobrevivenciaintervencion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaintervencion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sobrevivenciaintervencion',
            name='name',
        ),
        migrations.AddField(
            model_name='intervenciones',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de Intervencion'),
        ),
    ]
