# Generated by Django 4.2.5 on 2023-12-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0004_alter_podaintervencion_intervenciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaintervencion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='podaintervencion',
            name='users',
        ),
    ]
