# Generated by Django 4.2.5 on 2023-12-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0005_remove_podaintervencion_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaintervencion',
            name='porc_removido2',
        ),
        migrations.CreateModel(
            name='RaleoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('criterio', models.CharField(max_length=100, null=True, verbose_name='Criterio')),
                ('arboles_extraidos', models.IntegerField(blank=True, null=True)),
                ('arboles_podados', models.IntegerField(blank=True, null=True)),
                ('dap', models.FloatField(blank=True, null=True)),
                ('porc_removido', models.FloatField(blank=True, null=True)),
                ('intensidad', models.FloatField(blank=True, null=True)),
                ('levante', models.FloatField(blank=True, null=True)),
                ('intervenciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raleo_intervencion', to='intervenciones.intervenciones')),
            ],
        ),
    ]
