# Generated by Django 4.2.5 on 2023-12-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0005_remove_podaintervencion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenciones',
            name='superficie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
