# Generated by Django 4.2.5 on 2023-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0006_intervenciones_superficie'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaintervencion',
            name='area_basal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
