# Generated by Django 4.2.5 on 2023-12-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0006_remove_podaintervencion_porc_removido2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raleointervencion',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raleointervencion',
            name='dmsm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
