# Generated by Django 4.2.5 on 2023-12-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0008_alter_intervenciones_type_talarazaintervencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaintervencion',
            name='intervenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poda_intervencion', to='intervenciones.intervenciones'),
        ),
        migrations.AlterField(
            model_name='sobrevivenciaintervencion',
            name='intervenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrevivencia_intervencion', to='intervenciones.intervenciones'),
        ),
    ]
