# Generated by Django 4.2.5 on 2023-12-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_intervencionestypes_color'),
        ('intervenciones', '0011_intervenciones_intervenciones_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenciones',
            name='intervenciones_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_type_intervencion', to='configuration.intervencionestypes'),
        ),
    ]
