# Generated by Django 4.2.5 on 2023-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
