# Generated by Django 4.2.5 on 2023-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_users_firstname_users_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
    ]
