# Generated by Django 4.2.5 on 2023-09-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_users_firstname_remove_users_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('AG', 'General Administrator'), ('AA', 'Area Administrator'), ('AAWP', 'Area Administrator Witouth Permission'), ('DE', 'Data Entry')], default='DE', max_length=10, verbose_name='Role'),
        ),
    ]
