# Generated by Django 4.2.5 on 2023-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Nombre de usuario'),
        ),
    ]
