# Generated by Django 4.2.5 on 2023-09-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
