# Generated by Django 4.2.5 on 2023-10-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_users_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
