# Generated by Django 4.2.5 on 2023-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
