# Generated by Django 4.2.5 on 2023-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodales',
            name='cod_sap',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Código'),
        ),
    ]
