# Generated by Django 4.2.5 on 2023-12-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0001_initial'),
        ('rodales', '0002_alter_rodales_cod_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodales',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_rodales', to='empresas.empresas'),
        ),
        migrations.AlterField(
            model_name='rodales',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_rodales', to=settings.AUTH_USER_MODEL),
        ),
    ]
