# Generated by Django 4.2.5 on 2024-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0002_rodales_objnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodales',
            name='objnr',
        ),
        migrations.AddField(
            model_name='rodales',
            name='sap_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='sap_id'),
        ),
    ]
