# Generated by Django 4.2.5 on 2023-12-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0004_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
