# Generated by Django 4.2.5 on 2024-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0004_rodales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodales',
            name='cod_sap',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='rodales',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rodales',
            name='sap_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='sap_id'),
        ),
    ]
