# Generated by Django 4.2.5 on 2024-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodales', '0005_alter_rodales_cod_sap_alter_rodales_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodales',
            name='is_sap',
            field=models.BooleanField(default=True, verbose_name='Es SAP'),
        ),
    ]
