# Generated by Django 4.2.5 on 2023-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emsefor',
            fields=[
                ('emsefor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Emsefor')),
                ('contratista', models.CharField(blank=True, max_length=100, verbose_name='Contratista')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección de la Emsefor')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono de la Emsefor')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT de la Emsefor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.TextField()),
            ],
        ),
    ]
