# Generated by Django 4.2.5 on 2024-04-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
        ('emsefor', '0002_emsefor_sap_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmseforMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('emsefor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsefor.emsefor')),
                ('maquinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquinas')),
            ],
        ),
        migrations.AddField(
            model_name='emsefor',
            name='maquinas',
            field=models.ManyToManyField(through='emsefor.EmseforMaquinas', to='maquinas.maquinas'),
        ),
    ]
