# Generated by Django 4.2.5 on 2024-04-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
        ('emsefor', '0003_emseformaquinas_emsefor_maquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emsefor',
            name='maquinas',
            field=models.ManyToManyField(related_name='emsefor_maquinas', through='emsefor.EmseforMaquinas', to='maquinas.maquinas'),
        ),
    ]
