# Generated by Django 4.2.5 on 2024-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsefor', '0005_alter_emseformaquinas_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emseformaquinas',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
